# -*- coding: utf-8 -*-
"""Food Delivery Apps 316_323_335_328.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxGxPJl-IgSayAzsirpLsmOo3zZTxyXG
"""

# ==========================================
# 1. IMPORT LIBRARIES
# ==========================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# 2. LOAD DATASET
# ==========================================
df = pd.read_csv("/content/swiggy.csv")

# Fix column names
df.columns = df.columns.str.lower()
df.rename(columns={"delivery time": "delivery_time"}, inplace=True)

print("Columns:", df.columns)
print(df.head())

# ==========================================
# 3. DATA CLEANING
# ==========================================
df = df.drop_duplicates()
df = df.dropna()

print("\nAfter Cleaning Shape:", df.shape)

# ==========================================
# 4. BASIC STATISTICS
# ==========================================
print("\n--- STATISTICS ---")
print(df["delivery_time"].describe())

# ==========================================
# 5. OUTLIER REMOVAL (IQR METHOD)
# ==========================================
Q1 = df["delivery_time"].quantile(0.25)
Q3 = df["delivery_time"].quantile(0.75)
IQR = Q3 - Q1

df_clean = df[(df["delivery_time"] >= Q1 - 1.5 * IQR) &
              (df["delivery_time"] <= Q3 + 1.5 * IQR)]

print("\nBefore:", df.shape)
print("After Outlier Removal:", df_clean.shape)

# ==========================================
# 6. FEATURE ENGINEERING (VALID ONLY)
# ==========================================

# Delivery speed category
df_clean["delivery_speed"] = pd.cut(
    df_clean["delivery_time"],
    bins=[0, 30, 60, 200],
    labels=["Fast", "Medium", "Slow"]
)

# Price category
df_clean["price_category"] = pd.cut(
    df_clean["price"],
    bins=[0, 200, 400, 1000],
    labels=["Low", "Medium", "High"]
)

# Cost efficiency (valid derived metric)
df_clean["cost_efficiency"] = df_clean["price"] / df_clean["delivery_time"]

# ==========================================
# 7. CITY ANALYSIS
# ==========================================
city_avg = df_clean.groupby("city")["delivery_time"].mean().sort_values()
city_std = df_clean.groupby("city")["delivery_time"].std()

# ==========================================
# 8. VISUALIZATIONS (MEANINGFUL)
# ==========================================

# 1. Delivery Time Distribution
plt.figure()
sns.histplot(df_clean["delivery_time"], kde=True)
plt.title("Distribution of Delivery Time")
plt.xlabel("Delivery Time")
plt.show()

# 2. Delivery Time by City
plt.figure()
sns.boxplot(x="city", y="delivery_time", data=df_clean)
plt.xticks(rotation=45)
plt.title("Delivery Time Variation Across Cities")
plt.show()

# 3. Average Delivery Time by City
plt.figure()
city_avg.plot(kind="bar")
plt.title("Average Delivery Time by City")
plt.ylabel("Time")
plt.show()

# 4. Delivery Speed Category
plt.figure()
sns.countplot(x="delivery_speed", data=df_clean)
plt.title("Delivery Speed Distribution")
plt.show()

# 5. Price vs Delivery Time
plt.figure()
sns.scatterplot(x="price", y="delivery_time", data=df_clean)
plt.title("Price vs Delivery Time")
plt.show()

# 6. Delivery Time by Price Category
plt.figure()
sns.boxplot(x="price_category", y="delivery_time", data=df_clean)
plt.title("Delivery Time vs Price Category")
plt.show()

# 7. Cost Efficiency Distribution
plt.figure()
sns.histplot(df_clean["cost_efficiency"], kde=True)
plt.title("Cost Efficiency Distribution")
plt.show()

# 8. Correlation Heatmap
plt.figure()
sns.heatmap(df_clean[["price", "delivery_time", "cost_efficiency"]].corr(),
            annot=True)
plt.title("Correlation Matrix")
plt.show()

# 9. Consistency (Std Dev by City)
plt.figure()
city_std.plot(kind="bar")
plt.title("Delivery Time Consistency by City")
plt.ylabel("Std Deviation")
plt.show()

# ==========================================
# 9. INSIGHTS
# ==========================================

print("\n--- INSIGHTS ---")

print("Average Delivery Time:", round(df_clean["delivery_time"].mean(), 2))
print("Fastest City:", city_avg.idxmin())
print("Slowest City:", city_avg.idxmax())

print("\nTop 3 Fast Cities:\n", city_avg.head(3))
print("\nTop 3 Slow Cities:\n", city_avg.tail(3))

print("\n90% Deliveries under:",
      round(df_clean["delivery_time"].quantile(0.9), 2))

print("\nKey Findings:")
print("- Delivery time varies significantly across cities")
print("- Most deliveries fall in medium speed category")
print("- Price has weak correlation with delivery time")
print("- Some cities show high inconsistency (service variability)")
print("- Expensive orders are not always delivered faster")